spring.application.name=JavaMiniGames

# Port ??? 5332 ??? Default 5432 ??? ????????? (????????????? 5332 ???????????? ????????)
spring.datasource.url=jdbc:postgresql://localhost:5432/JavaMiniGames

# Username ??? default 'postgres' ??????????? (??? create ?????????? user ? ????????????????)
spring.datasource.username=postgres

# PostgreSQL install ???????? ????????? password ???????? ???????
spring.datasource.password=password

spring.security.user.name=admin
spring.security.user.password=12345

spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Dialect ??? ?????? ????????????????? (???????? ??????????? Dialect error ????????????????????)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true